export const METRIC_DEFINITIONS = {
  pointDiff: {
    labelJa: '得失点差',
    labelEn: 'Points Differential',
    formulaJa: '得点 − 失点',
    formulaEn: 'Points For − Points Against',
    suffix: '',
    decimals: 1,
    type: 'calculated',
  },
  winRate: {
    labelJa: '勝率',
    labelEn: 'Win Rate',
    formulaJa: '勝利試合数 ÷ 勝敗確定試合数 × 100',
    formulaEn: 'Wins ÷ matches with a known result × 100',
    suffix: '%',
    decimals: 1,
    type: 'calculated',
  },
  pointsPerMatch: {
    labelJa: '1試合当たり得点',
    labelEn: 'Points per Match',
    formulaJa: '選択範囲の得点合計 ÷ 対象試合数',
    formulaEn: 'Total Points For ÷ selected matches',
    suffix: '',
    decimals: 1,
    type: 'calculated',
  },
  triesPerMatch: {
    labelJa: '1試合当たりトライ',
    labelEn: 'Tries per Match',
    formulaJa: '選択範囲のトライ合計 ÷ 対象試合数',
    formulaEn: 'Total Tries ÷ selected matches',
    suffix: '',
    decimals: 1,
    type: 'calculated',
  },
  pointsPer100Metres: {
    labelJa: '100m当たり得点',
    labelEn: 'Points per 100 Metres',
    formulaJa: '得点 ÷ 獲得メートル × 100',
    formulaEn: 'Points For ÷ Metres × 100',
    suffix: '',
    decimals: 2,
    type: 'calculated',
  },
  triesPer100Metres: {
    labelJa: '100m当たりトライ',
    labelEn: 'Tries per 100 Metres',
    formulaJa: 'トライ ÷ 獲得メートル × 100',
    formulaEn: 'Tries ÷ Metres × 100',
    suffix: '',
    decimals: 2,
    type: 'calculated',
  },
  metresPerCarry: {
    labelJa: '1キャリー当たりメートル',
    labelEn: 'Metres per Carry',
    formulaJa: '獲得メートル ÷ キャリー',
    formulaEn: 'Metres ÷ Carries',
    suffix: '',
    decimals: 2,
    type: 'calculated',
  },
  cleanBreaksPer100Carries: {
    labelJa: '100キャリー当たりクリーンブレイク',
    labelEn: 'Clean Breaks per 100 Carries',
    formulaJa: 'クリーンブレイク ÷ キャリー × 100',
    formulaEn: 'Clean Breaks ÷ Carries × 100',
    suffix: '',
    decimals: 1,
    type: 'calculated',
  },
  defendersBeatenPerCarry: {
    labelJa: '1キャリー当たりディフェンダー突破',
    labelEn: 'Defenders Beaten per Carry',
    formulaJa: 'ディフェンダー突破 ÷ キャリー',
    formulaEn: 'Defenders Beaten ÷ Carries',
    suffix: '',
    decimals: 2,
    type: 'calculated',
  },
  turnoverDifferential: {
    labelJa: 'ターンオーバー差',
    labelEn: 'Turnover Differential',
    formulaJa: 'ターンオーバー獲得 − ターンオーバー喪失',
    formulaEn: 'Turnovers Won − Turnovers Conceded',
    suffix: '',
    decimals: 1,
    type: 'calculated',
  },
  penaltiesPerMatch: {
    labelJa: '1試合当たり反則',
    labelEn: 'Penalties per Match',
    formulaJa: '選択範囲の反則合計 ÷ 対象試合数',
    formulaEn: 'Total Penalties Conceded ÷ selected matches',
    suffix: '',
    decimals: 1,
    type: 'calculated',
  },
  tackleSuccess: {
    labelJa: 'タックル成功率',
    labelEn: 'Tackle Success',
    formulaJa: 'タックル ÷（タックル＋ミスタックル）× 100',
    formulaEn: 'Tackles ÷ (Tackles + Missed Tackles) × 100',
    suffix: '%',
    decimals: 1,
    type: 'calculated',
  },
  ruckSuccess: {
    labelJa: 'ラック成功率',
    labelEn: 'Ruck Success',
    formulaJa: 'ラック獲得 ÷（ラック獲得＋ラック喪失）× 100',
    formulaEn: 'Rucks Won ÷ (Rucks Won + Rucks Lost) × 100',
    suffix: '%',
    decimals: 1,
    type: 'calculated',
  },
  pointsAgainst: {
    labelJa: '失点',
    labelEn: 'Points Against',
    formulaJa: '試合で許した得点',
    formulaEn: 'Points conceded in the match',
    suffix: '',
    decimals: 1,
    type: 'raw',
  },
  turnoversConceded: {
    labelJa: 'ターンオーバー喪失',
    labelEn: 'Turnovers Conceded',
    formulaJa: '試合で失ったターンオーバー数',
    formulaEn: 'Turnovers conceded in the match',
    suffix: '',
    decimals: 1,
    type: 'raw',
  },
};

export const ANALYSIS_METRIC_KEYS = [
  'pointDiff',
  'winRate',
  'pointsPerMatch',
  'triesPerMatch',
  'pointsPer100Metres',
  'triesPer100Metres',
  'metresPerCarry',
  'cleanBreaksPer100Carries',
  'defendersBeatenPerCarry',
  'turnoverDifferential',
  'penaltiesPerMatch',
  'tackleSuccess',
  'ruckSuccess',
];

export const COMPARISON_METRIC_KEYS = ANALYSIS_METRIC_KEYS;
export const TREND_METRIC_KEYS = ANALYSIS_METRIC_KEYS;

export function getMetricDefinition(metricKey) {
  return METRIC_DEFINITIONS[metricKey] || {
    labelJa: metricKey,
    labelEn: metricKey,
    formulaJa: metricKey,
    formulaEn: metricKey,
    suffix: '',
    decimals: 1,
    type: 'unknown',
  };
}
