export const METRIC_CATEGORIES = [
  {
    id: 'results',
    labelJa: '結果・得点力',
    labelEn: 'Results & Scoring',
    descriptionJa: '勝敗と、1試合当たりの得点生産を確認します。',
    descriptionEn: 'Outcome and scoring production per match.',
    metricKeys: [
      'pointDiff',
      'winRate',
      'pointsPerMatch',
      'triesPerMatch',
    ],
  },
  {
    id: 'scoringEfficiency',
    labelJa: '得点効率',
    labelEn: 'Scoring Efficiency',
    descriptionJa: '獲得した前進を得点・トライへ変換した効率を確認します。',
    descriptionEn: 'How efficiently territorial gain became points and tries.',
    metricKeys: ['pointsPer100Metres', 'triesPer100Metres'],
  },
  {
    id: 'attackingEfficiency',
    labelJa: '攻撃効率',
    labelEn: 'Attacking Efficiency',
    descriptionJa: 'キャリーによる前進とラインブレイクの効率を確認します。',
    descriptionEn: 'Carry gain and line-breaking efficiency.',
    metricKeys: [
      'metresPerCarry',
      'cleanBreaksPer100Carries',
      'defendersBeatenPerCarry',
    ],
  },
  {
    id: 'possessionDiscipline',
    labelJa: 'ボール管理・規律',
    labelEn: 'Possession & Discipline',
    descriptionJa: 'ボール獲得・喪失の差と反則負担を確認します。',
    descriptionEn: 'Net turnover position and disciplinary cost.',
    metricKeys: ['turnoverDifferential', 'penaltiesPerMatch'],
  },
  {
    id: 'defenceRetention',
    labelJa: '守備・ボール保持',
    labelEn: 'Defence & Retention',
    descriptionJa: 'タックル遂行とラック保持の安定性を確認します。',
    descriptionEn: 'Tackle execution and ruck-retention stability.',
    metricKeys: ['tackleSuccess', 'ruckSuccess'],
  },
];

export const RELATIONSHIP_PRESETS = [
  {
    id: 'carryGainResult',
    labelJa: 'キャリー前進効率と試合結果',
    labelEn: 'Carry gain efficiency and result',
    questionJa: '1キャリー当たりの前進量が大きい試合ほど、得失点差は良かったか。',
    questionEn: 'Did matches with greater metres per carry also have a better points differential?',
    xMetric: 'metresPerCarry',
    yMetric: 'pointDiff',
  },
  {
    id: 'cleanBreakResult',
    labelJa: 'クリーンブレイク効率と試合結果',
    labelEn: 'Clean-break efficiency and result',
    questionJa: '100キャリー当たりのクリーンブレイクが多い試合ほど、得失点差は良かったか。',
    questionEn: 'Did matches with more clean breaks per 100 carries also have a better points differential?',
    xMetric: 'cleanBreaksPer100Carries',
    yMetric: 'pointDiff',
  },
  {
    id: 'defendersBeatenResult',
    labelJa: '突破効率と試合結果',
    labelEn: 'Defender-beating efficiency and result',
    questionJa: '1キャリー当たりのディフェンダー突破が多い試合ほど、得失点差は良かったか。',
    questionEn: 'Did matches with more defenders beaten per carry also have a better points differential?',
    xMetric: 'defendersBeatenPerCarry',
    yMetric: 'pointDiff',
  },
  {
    id: 'turnoverResult',
    labelJa: 'ターンオーバー差と試合結果',
    labelEn: 'Turnover differential and result',
    questionJa: 'ターンオーバー差が良い試合ほど、得失点差は良かったか。',
    questionEn: 'Did a better turnover differential accompany a better points differential?',
    xMetric: 'turnoverDifferential',
    yMetric: 'pointDiff',
  },
  {
    id: 'disciplineResult',
    labelJa: '反則と試合結果',
    labelEn: 'Discipline and result',
    questionJa: '反則が少ない試合ほど、得失点差は良かったか。',
    questionEn: 'Did matches with fewer penalties have a better points differential?',
    xMetric: 'penaltiesPerMatch',
    yMetric: 'pointDiff',
  },
  {
    id: 'tackleConcession',
    labelJa: 'タックル成功率と失点',
    labelEn: 'Tackle success and points conceded',
    questionJa: 'タックル成功率が高い試合ほど、失点は少なかったか。',
    questionEn: 'Did matches with higher tackle success concede fewer points?',
    xMetric: 'tackleSuccess',
    yMetric: 'pointsAgainst',
  },
  {
    id: 'ruckTurnovers',
    labelJa: 'ラック成功率とターンオーバー喪失',
    labelEn: 'Ruck success and turnovers conceded',
    questionJa: 'ラック成功率が高い試合ほど、ターンオーバー喪失は少なかったか。',
    questionEn: 'Did matches with higher ruck success concede fewer turnovers?',
    xMetric: 'ruckSuccess',
    yMetric: 'turnoversConceded',
  },
];
